name = "ADAPT"
uuid = "cf1f529f-af3f-4d7a-b5f1-0e7d3fdd5852"
authors = ["Kyle Sherbert <kyle.sherbert@vt.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
